# Generated by Django 4.1 on 2022-12-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=600)),
                ('image', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('numdis', models.IntegerField(max_length=10)),
            ],
        ),
    ]
